### ISSUE TITLE
Structure field broken if no entry

### ISSUE THREAD

**Issue by bnomei** [getkirby/panel#1091] opened 2017-08-21 08:19 UTC
using 2.5.4. existing blueprint. added a structure field definition. switched to panel to add some data. but field is broken.

```Invalid argument supplied for foreach()```

if i add a first value editing the content file it works as intended.

**Comment by lukasbestle** [comment] 2017-08-21 08:24
This is a duplicate of #1080. Does the version from the develop branch work for you?

**Closed by lukasbestle** 2017-08-21 08:24 UTC
