### ISSUE TITLE
Idea: Page as whole Drag-n-Drop upload area

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#343] opened 2015-01-25 10:01 UTC
Seriously: I'm sick of this modal dialog: 
![bildschirmfoto 2015-01-25 um 10 34 02](https://cloud.githubusercontent.com/assets/980778/5891032/d527cfa8-a47d-11e4-9da3-7de118bd7d0e.png)

It's like a mode that I firstly have to activate before I work intuitively. But a mode that's required for a simple action is nothing normal or intuitive because you don't think like that.

My idea: make a whole Page in the Panel as a drag to upload area so I don't have to activate first the Upload mode. 

### A user story:
When I want to edit a page and add a nice photo into my portfolio, I just start dragging the photo into the browser window. The Panel recognizes that and takes itself into something like an "upload mode" which means I see a giant upload area. So I don't have to put my photo directly into a small area but I can upload it nearly blindly just by dragging it anywhere into the browser window. 

That's what I call intuitive. I don't have to mind about *where* I have to drag my files but just drag it into the window.

### Another user story: file upload isn't allowed
Yes that's a case you also have to watch. When I'm start dragging a file into a Page on which I'm not allowed to upload any file, I simply have to be informed by a message. Something like "Sorry, Uploading files is not allowed on Template [TEMPLATE NAME]" (or something less technical). 
But *why* do you have to think also about this user story? Deadly simple: if you drag a file into a page which doesn't have something like a giant upload area the browser just opens the file you've dragged in. That's frustrating - and you have to avoid frustrations!

### Page intern drag and drop
Kirby has a cool feature which I'm using very often: dragging files and pages into the textarea to make a link or display an image. But what happens to the upload area - because this is also a drag and drop area? Simply nothing. Dragging something inside the browser window means that you're interact directly with the UI. Dragging things outside into the window means upload. 

What do you think? I'm sure that this isn't something you would do in a day or two but I'm sure that this simple feature would be loved by the users. And this is not the only one: if you want to reorder your sites, why do I also have to go to the "Sites" overview? 
Mostly it's difficult to develop features which ends up into deadly simple interaction patterns but it's worth every effort.

**Comment by jakobploens** [comment] 2015-01-25 15:03
+100. Great Idea, I also often thought about the whole-page drag'n'drop area, as well as reordering of sites and files in the main window. Like your concept very much!

**Comment by byybora** [comment] 2015-03-12 15:57
+1

**Comment by dgdsp** [comment] 2015-03-26 13:30
+1

**Comment by bastianallgeier** [comment] 2015-03-31 08:55
I'm working on this. It's also a duplicate of this issue, so I'm going to close it for now: #66

**Closed by bastianallgeier** 2015-03-31 08:55 UTC
