### ISSUE TITLE
panel.page.move hook does not seem to work in 2.4.0 and 2.4.0 dev

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#960] opened 2016-11-24 10:25 UTC

**Comment by ShawnCollier** [comment] 2016-11-25 01:06
I can confirm this on my end as well, I was attempting to use this after seeing that changing the URL triggers this hook (https://forum.getkirby.com/t/possible-to-hook-change-of-url-for-default-language/3915).

(I was going to create a forum post about this, but noticed this issue and thought it'd be better to comment here instead of making another thread there, if that's alright?)

**Comment by ShawnCollier** [comment] 2016-11-26 18:13
https://github.com/getkirby/panel/commit/63c20ae2a3f497a8568ed9349b139db0b37b9639

I don't use GitHub regularly outside of hosting my personal website, so I have no idea how pull requests and the like work, but I do think I know what the cause of this issue is.

It appears to be very similar to that above issue. When I changed line 271 in the same file to:

`kirby()->trigger('panel.page.move', [$this, $old]);`

That made the console statement print out in my debugger. The URL change also happened, so it appears everything worked as expected then? Unless there's something deeper code-wise I'm unaware of.

**Comment by bastianallgeier** [comment] 2016-12-06 21:24
This is now fixed on the develop branch.

**Closed by bastianallgeier** 2016-12-06 21:24 UTC
Labels: bug
