### ISSUE TITLE
Select field query options doesnt working on site page

### ISSUE THREAD

**Issue by byybora** [getkirby/panel#392] opened 2015-03-14 11:28 UTC
I tried to do logo select area from site(site blueprint) page like following:

`````
site_logo:
	label: Site Logo
	type: select
	options: query
	query: 
		page: home
		fetch: images
		value: '{{filename}}'
		text: '{{filename}}'
`````

I tried same blueprint on home page, it's working but on site page, dropdown is empty and home page have 4 images.

**Comment by bastianallgeier** [comment] 2015-03-30 14:32
Try 

```
page: / 
```

instead

**Comment by byybora** [comment] 2015-03-30 14:48
I tried `/` on site blueprint doesnt list anything and on another page throw error:

> Call to a member function images() on a non-object in

**Comment by byybora** [comment] 2015-04-01 08:40
@bastianallgeier by the way, files work on site page? I added `files: true` on `site.txt` but i couldnt get any effect.

**Comment by distantnative** [comment] 2015-04-01 10:27
Works for me even without adding anything to the blueprint:
![screen shot 2015-04-01 at 12 25 43](https://cloud.githubusercontent.com/assets/3788865/6939198/6d859d8c-d86a-11e4-8b85-e246f504fa93.png)

**Comment by byybora** [comment] 2015-04-01 10:30
I'm on 2.0.6, should try 2.1.0 ;) Thanks

**Comment by andi242** [comment] 2015-04-03 08:24
I'm on 2.0.7 and site files are already working.

But I can't get the select field get to grab the 'site files'.
It won't work with a `/` query either.

**Comment by distantnative** [comment] 2015-04-03 09:34
Have you tried it with 2.1, @andi242?

**Comment by andi242** [comment] 2015-04-03 11:47
Yes, 2.1 does no difference for me :)

**Comment by andi242** [comment] 2015-04-29 18:41
I changed the core files to your commit, and realized that files in `site()` are adressed with `/content` in the url now. Which is fine for me, but not as like as before, if I remember correctly.

In addition attachments do now have a double `//`in the path (like in http://www.yoursite.com/content//image.jpg). Not sure if this is caused by this commit, haven't seen this before, though.

**Comment by distantnative** [comment] 2015-04-29 19:28
Ok, I realized that no matter with or without my commit (adding `site()`) the public path seems to include double `//`
![screen shot 2015-04-29 at 21 21 26](https://cloud.githubusercontent.com/assets/3788865/7399388/e13e99d4-eeb5-11e4-841f-49c4d5c7c86a.png)

When you write
>are adressed with /content in the url now

do you mean, if you get them for example
```php
<?php echo $site->images()->first()->url() ?>
``
?

Cause for me this returns/displays again `http://kirby:8888/content//cimg2908.jpg`, no matter if with or without the changes. Or do you refer to something additional? Anyways, will try to find that double slash issue.

**Comment by andi242** [comment] 2015-04-30 06:53
Thanks for clarifying. I was not sure about the root cause, so every thing appears to be fine with your fix.
(decent one! :) )

**Comment by distantnative** [comment] 2015-05-06 14:28
The fix has just been added to the develop branch and will be included in the next release.

**Closed by distantnative** 2015-05-06 14:28 UTC
Labels: bug, in progress

**Comment by moritzz** [comment] 2015-06-22 15:07
@distantnative: What's the solution to the original bug report/question now? I tired all proposed ones above (on 2.1.0) and none of these work —apparently because the discussion took off from the original issue? Can you please re-open this?
