### ISSUE TITLE
Sorting function for structure fields

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#318] opened 2015-01-02 17:35 UTC
I use the structure field of a simple calendar and it works fine. I can sort the events at the output in `my template.php` with `a::sort` but it would be nice if the events in the panel could be viewed sorted to.

**Comment by texnixe** [comment] 2015-03-31 21:12
+1

**Comment by vicegold** [comment] 2015-05-10 14:42
@tweh  could you please post the code you have working with ```a::sort``` here? Don't get it to work.

**Comment by tweh** [comment] 2015-05-11 12:15
Sure! This is (a part of) my blueprint:

      calendar:
        label: Einträge
        type: structure
        entry: >
          <strong>{{title}}</strong><br>
          <span class="structure-label">Beschreibung</span> {{description}}<br>
          <span class="structure-label">Datum/Zeit</span> {{date}}, {{starttime}}–{{endtime}}<br>
          <span class="structure-label">Ort</span> {{place}}
        fields:
          title:
            label: Titel
            type: text
          description:
            label: Beschreibung
            type: textarea
            size: small
          place:
            label: Ort
            type: text
            required: true
          date:
            label: Datum
            type: date
            format: DD.MM.YYYY
            required: true
          starttime:
            label: Startzeit
            type: time
            interval: 15
            required: true
          endtime:
            label: Endzeit
            type: time
            interval: 15
            help: Wenn End- und Startzeit gleich sind, wird nur die Startzeit ausgegeben.

And this is the corresponding part from the template:

    
    <?php
        $events = yaml($page->calendar());
    
        function filterFutureEvents($event) {
            return(strtotime($event['date'])-time() >= 0);
        }
        function filterPastEvents($event) {
            return(strtotime($event['date'])-time() < 0);
        }
    
        $futureEvents = a::sort(array_filter($events, 'filterFutureEvents'),'date','asc');
        $pastEvents = a::sort(array_filter($events, 'filterPastEvents'),'date','desc');
    ?>
    
    
    <div class="calendar-category">
        <h2><?php echo $page->lbfuture() ?></h2>
        <?php if (!empty($futureEvents)) : ?>
        <?php foreach ($futureEvents as $event): ?>
            <?php snippet('event',
                          array(
                              'event' => $event,
                              'datelabel' => $page->lbdate(),
                              'placelabel' => $page->lbplace()
                          )
                         ) ?>
        <?php endforeach ?>
        <?php else: ?>
        <?php echo $page->txtnoevents()->kt() ?>
        <?php endif ?>
    </div>
    
    
    <?php if (!empty($pastEvents)) : ?>
    <div class="calendar-category past-events">
        <h2><?php echo $page->lbpast() ?></h2>
        <?php foreach ($pastEvents as $event): ?>
            <?php snippet('event',
                          array(
                              'event' => $event,
                              'datelabel' => $page->lbdate(),
                              'placelabel' => $page->lbplace()
                          )
                         ) ?>
        <?php endforeach ?>
    </div>
    <?php endif ?>

I hope this helps …

**Comment by distantnative** [comment] 2016-02-06 21:21
Duplicate of #722.

Sorting of structure fields in the template can also be done now by `->toStructure()->sortBy('date', 'asc')`.

**Closed by distantnative** 2016-02-06 21:21 UTC
Labels: idea
