### ISSUE TITLE
Field assets are not registered correctly with the new registry

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#825] opened 2016-04-12 10:53 UTC
https://forum.getkirby.com/t/register-plugin-with-set/3827

**Comment by puckey** [comment] 2016-04-12 13:03
+1

**Comment by lukasbestle** [comment] 2016-04-15 09:46
Seems like this doesn't only apply to the registry but also to "normal" fields: #831.

**Comment by distantnative** [comment] 2016-04-19 09:58
I think this is a duplicate of #831 - and since that one is the more general one, I'm closing this issue.

**Closed by distantnative** 2016-04-19 09:59 UTC
