### ISSUE TITLE
pages:false in site blueprint and Edit button in panel

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#431] opened 2015-04-11 05:20 UTC
If `pages:false` is set in the `site.php` blueprint, there is still an **Edit** button on the dashboard of the panel. Clicking it comes up with 'page not found'
Simple to remove it or more complicated to allow sorting but not creation..

**Comment by distantnative** [comment] 2015-04-28 13:36
Should be resolved together with panel permissions after the v2.1.

**Comment by mingyeungs** [comment] 2015-05-21 11:04
the **Edit** button is still there in the v2.1 release. Is it the intended behavior?
Meanwhile, I'm using the following lines to hide the buttons:
`div.dashboard-section:first-child span.hgroup-options{ visibility: hidden; }`

**Comment by distantnative** [comment] 2015-05-21 11:27
Permissions haven't made it into the 2.1 release but are still coming in a next release.

**Comment by bastianallgeier** [comment] 2015-10-06 15:04
This is fixed on the decruft branch and will finally be in the next release.

**Closed by bastianallgeier** 2015-10-06 15:04 UTC
Labels: in progress
