### ISSUE TITLE
Disable panel cache?

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#718] opened 2016-01-01 23:59 UTC
Is there a way to disable the panel's cache? This is a problem when I'm copying + pasting a lot of info in that gets parsed incorrectly (not by any fault of Kirby). I end up doing some quick work in the actual .txt files to get things in order, but I need to log out / log in again to see these changes reflected on the page.

**Comment by texnixe** [comment] 2016-01-02 01:39
Does this regards structure fields or all sorts of fields? I know there is an issue with structure fields, their content get loaded from the cache rather then from the file. But with other fields, refreshing the page should do the job without your having to logout/-in again?

**Comment by SQbiz** [comment] 2016-01-04 06:28
Yes, it's only with structure fields

**Comment by texnixe** [comment] 2016-01-04 10:28
Then it's a duplicate of issue https://github.com/getkirby/panel/issues/687 which has been closed and related to https://github.com/getkirby/panel/issues/688

**Closed** 2016-01-04 14:38 UTC
