### ISSUE TITLE
Checkbox inside Structure always madatory (v2.2 beta)

### ISSUE THREAD

**Issue by svnt** [getkirby/panel#599] opened 2015-10-28 21:41 UTC
Checkbox inside Structure always madatory (must be checked before save).

**Comment by lukasbestle** [comment] 2015-10-28 22:08
Do you also have this issue if the checkbox is outside of a structure field?

**Comment by texnixe** [comment] 2015-10-29 10:11
Yes, this is also an issue outside of a structure field.

**Comment by lukasbestle** [comment] 2015-10-29 10:12
Then this is a duplicate of #592.

**Closed by lukasbestle** 2015-10-29 10:12 UTC
