### ISSUE TITLE
Ability to change label for Pages (per blueprint)

### ISSUE THREAD

**Issue by rooraggio** [getkirby/panel#721] opened 2016-01-03 22:59 UTC
I would like to change the label for 'pages' (in the left-hand toolbar) in the panel as I would any other field in the blueprint. It would be nice to have a specific page template as a 'post type' and having the subpages with a custom title relevant to the post type would be super rad.

**Comment by lukasbestle** [comment] 2016-01-04 14:44
This is a duplicate of #248.

**Closed by lukasbestle** 2016-01-04 14:44 UTC
