### ISSUE TITLE
Hide URL-appendix 

### ISSUE THREAD

**Issue by Moorst** [getkirby/panel#782] opened 2016-02-25 12:12 UTC
Is it possible to hide the URL-appendix field, or at least disable it?

I'm using kirby for a one page site and I don't want the user editing the URL-appendix for what is being used as a "section" of the page. If they do edit this, it change the class of the section and therefore messes with the css associated.

**Comment by texnixe** [comment] 2016-02-25 12:32
Currently, the only way to hide the field is via a custom panel stylesheet. I close this issue because this is a duplicate of https://github.com/getkirby/panel/issues/693

**Closed** 2016-02-25 12:32 UTC
