### ISSUE TITLE
Text like “\newline” vs. structure field in panel

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#538] opened 2015-07-30 17:35 UTC
I came to a problem when building my site. I git some pages where I like to show LaTeX code. I use a structured field but entries like `\newline` (which is a common LaTeX macro don’t get saved properly, i.e. the `\n` is cut of and interpreted as new line control sequence.

__How to reproduce:__

1. download starter kit

2. add the following field to `blueprints/default.php`

          test:
            label: Test-Field
            type: structure
            entry: {{text}}
            fields:
              text:
                label: Text
                type: text

3. go to the panel

4. edit a default page

5. add a new entry to the structure field

6. type in `\newline` and click “Add”

7. save the page

_Result:_ The entry is saved as `ewline` …

----

I also posted this as a [question in the forum](http://forum.getkirby.com/t/text-like-newline-vs-structure-field-in-panel/1723) …

**Comment by bastianallgeier** [comment] 2015-10-06 15:22
Sorry for the delay. I just tested this on my decruft branch and can't reproduce it with the new architecture. I'm pretty sure it was a javascript problem with the way structure fields worked before. Anywho, this will be fixed in the next release :)

**Closed by bastianallgeier** 2015-10-06 15:22 UTC
