### ISSUE TITLE
validate field not respected in 'add a new page' dialog

### ISSUE THREAD

**Issue by puckey** [getkirby/panel#860] opened 2016-06-02 12:32 UTC
when I add a validate option like 'max: 20' to the title field, it is not respected in the 'add a new page' dialog

**Comment by malvese** [comment] 2016-06-04 08:12
Just [wrote about this in the forum](https://forum.getkirby.com/t/validate-a-title-when-we-create-a-page/4306), so +1.
In my case, the title is a year so I would have liked to validate it as a `num` and with `min` value.

**Comment by lukasbestle** [comment] 2016-06-04 13:31
Duplicate of #845. Discussion continues there.

**Closed by lukasbestle** 2016-06-04 13:31 UTC
Labels: enhancement
