### ISSUE TITLE
Structure field is populated from cache rather than from file content

### ISSUE THREAD

**Issue by FabianSperrle** [getkirby/panel#687] opened 2015-11-30 08:21 UTC
[Just carrying this over from the forum: https://forum.getkirby.com/t/panel-doesnt-update-structure-fields-anymore/2650]

It seems that the panel does not handle structure fields properly anymore since 2.2. When the content file is changed while the user is logged in (e.g. via a signup controller) the content of the structure in the panel is not updated - even if there were no unsaved changes in the panel that would be overwritten. 

Logging out+in or picking a new browser makes the panel update again.

**Comment by bastianallgeier** [comment] 2015-12-02 20:12
I'm closing this since it's more or less a duplicate of the other issue.

**Closed by bastianallgeier** 2015-12-02 20:12 UTC

**Comment by FabianSperrle** [comment] 2015-12-03 07:03
It deals with a similar problem, but has a much higher severity. I would really love to see a bug fix for this, before you start to think about the more complex solutions to synchronise panel and content files.

When I change some fields in the content file, say the title and an entry to a structure field, and reload the panel, only the title is updated. The structure content gets populated from the cache. When I click save again in the panel, my changes to the file are overwritten by the panel.

This problem occurs as long as my session is active. Recently, I lost one week of signup-data because of this: the panel kept using the week-old cached content. It will **never** update its cache, unless I log out or start a new session on a different device. 

This is a bug in the current system, while the other issue describes a nice-to-have addition to it.

**Comment by distantnative** [comment] 2016-03-14 20:00
This has been fixed on the develop branch.
