### ISSUE TITLE
Some Dashboard Items not visible in Chrome (OSX)

### ISSUE THREAD

**Issue by Targoran** [getkirby/panel#653] opened 2015-11-14 20:44 UTC
In Chrome, some items in the dashboard seem to be missing. For example, the avatar/name of your profile dashboard widget aren't displayed. Firefox and Safari are working just fine.

<img width="474" alt="missing avatar" src="https://cloud.githubusercontent.com/assets/2758377/11165723/1da755b0-8b18-11e5-9f74-fd8b489f3989.png">

It's not only the avatar/name missing, but also the icons in the "last edited" widget.

Interesting enough, this problems doesn't appear when you resize the browser to the mobile view.

I'm using Chrome 46 on OSX (El Capitan, Yosemite)

**Comment by texnixe** [comment] 2015-11-14 20:57
This seems to be a duplicate of #555: https://github.com/getkirby/panel/issues/555

**Closed** 2015-11-14 20:59 UTC
