### ISSUE TITLE
Uploads slower (v.2.2 beta)

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#611] opened 2015-11-03 10:09 UTC
When there are a lot of files for the page (I know this is generally not a good idea to have a lot of them) there is a significant speed difference between the 2.1.1 and the 2.2 panel. For instance adding a file to a page that already has a 100 files happens fast on panel 2.1.1 but takes a very long time on panel 2.2 (looking at the spinner for around 15 seconds on localhost). The extra file is small (100kb). As I said it’s generally not a good idea to have a lot of files for a page, but I couldn’t help noticing this speed difference.

Update: it seems to be that it’s not the upload itself that’s taking long. The file appears quickly in the filesystem but the panel keeps showing the spinner.

**Comment by distantnative** [comment] 2015-11-09 18:04
Can't reproduce that. Put about 110 pdf files in a page and when I add another pdf file up to 100kb, it might not be lightning fast, but within 2-3 seconds at most.

Could you tell me what files that are or if you have any files settings in your blueprint? Cause I'd assume that it's rather a PHP error somewhere on the way, even after the upload as it looks like.

**Comment by iksi** [comment] 2015-11-09 18:29
They were jpegs. The site contains a lot of images, and the amount of files in the `/thumbs` folder went way over 10,000. I currently can’t reproduce it myself as I changed the way thumbs are handled: I’ve added a `thumbs.destination` function so that thumbnails are stored with the content itself. Files settings were as follows:

```YAML
files:
  fields:
    video:
      label: Video
      type: url
  sortable: true
````

**Comment by bastianallgeier** [comment] 2015-11-09 19:51
We should keep an eye on it, but close it for now. I guess it really had something to do with the thumbnails. I'm working on a better solution for that anyway.

**Closed by bastianallgeier** 2015-11-09 19:51 UTC

**Comment by iksi** [comment] 2015-11-09 20:09
👍🏼
