### ISSUE TITLE
Strange behavior on Cyrillic slug generation in panel

### ISSUE THREAD

**Issue by imikekgd** [getkirby/panel#724] opened 2016-01-05 21:36 UTC
Since 2.2 release Cyrillic slug generation in panel is unpredictable. It seems it issue of algorithm - not vocabulary

For example:

Название  -> nazv-ie - no second "а" and following "н" - dash instead
азвание  -> azvnie (just delete first letter - no second "а" good for remaining)
Призвание  -> prizvane - changed some first letters but wrong again - in this case no second "и" but everything is ok

etc...

Will try to find out myself and submit to git

**Comment by distantnative** [comment] 2016-02-13 18:18
Sorry, but could you be more clearer what the expected results would be? My Cyrillic is non-existent and this would help me trying to find the bug:

`Название` should result in `?`
`азвание` should result in `?`
`Призвание` should result in `?`

Thanks!

**Comment by texnixe** [comment] 2016-02-13 19:30
Название => nazvanie
азвание => azvanie
Призвание => prizvanie

**Comment by distantnative** [comment] 2016-02-13 20:18
Thnaks, @texnixe. I can tell at what code lines the problem is happening, but it seems to be related to encodings... :sos:

**Comment by distantnative** [comment] 2016-03-14 20:23
Might be related to https://github.com/getkirby/kirby/issues/124 as well.

**Comment by Furs1k** [comment] 2016-06-16 08:33
kirby-2.3.0 has been released, but the problem still exists, very annoying.
Let me remind you, this problem occurs only when you add a new page. If you tap the button "change URL" in the early created page, then everything is fine. Also, when you add a new file, there is no problems in the Cyrillic Url-appendix.
Maybe there is a temporary solution?
Thank you in advance for your help!

**Comment by jenstornell** [comment] 2016-06-16 08:36
@Furs1k Not a solution but maybe a workaround for you can be this plugin:

https://github.com/jenstornell/kirby-slug-modifier

**Comment by Furs1k** [comment] 2016-06-16 08:45
@jenstornell I tried your plugin, it does not help in that problem.
The problem is that the first word is processed normally, but the others turn into a mess.

**Comment by Furs1k** [comment] 2016-06-16 13:36
Issue Screenshots:
1) Dialog to add a new page - (the first word is processed normally, but the others turn into a mess)
![screen11](https://cloud.githubusercontent.com/assets/19970756/16118438/c28ef07c-33df-11e6-92d4-e98c3d92e516.png)
2) Tap the button "change URL" in the early created page - (everything is fine)
![screen12](https://cloud.githubusercontent.com/assets/19970756/16118519/16f61596-33e0-11e6-800c-87fdac11c154.png)
3) Dialog to add a new file - (everything is fine)
![screen13](https://cloud.githubusercontent.com/assets/19970756/16118545/3a33d354-33e0-11e6-97bc-2e05ff164e86.png)

**Comment by imikekgd** [comment] 2016-06-16 14:01
This issue is related to VOVELS - not words...
first vovel transcribes normally. but second (and any next vovels just
skips)

**Comment by imikekgd** [comment] 2016-10-03 15:53
it's not FIRST word issue - it's issue of LETTERS which were already transcribed. So "ааа-ллл" will became "а-л". So script just ignores second (and later) chars in string

**Comment by igorqr** [comment] 2016-11-08 14:40
@bastianallgeier fix the bug in 2.4.1 plz

**Comment by bastianallgeier** [comment] 2016-11-17 14:12
This is finally fixed on the develop branch. Sorry for the delay!!

**Closed by bastianallgeier** 2016-11-17 14:12 UTC
Labels: bug

**Comment by igorqr** [comment] 2016-11-17 14:15
Thank you! See more this problem (I think there's just correct) https://forum.getkirby.com/t/in-korean-some-problem-on-sortby-title-asc/5706/10

**Comment by Furs1k** [comment] 2016-11-17 15:57
Гуд, Сергей спрашивал про проверку текста на уникальность, я сказал text.ru

С уважением Андрей Суслов
