### ISSUE TITLE
Files not sortable by default in 2.5.7?

### ISSUE THREAD

**Issue by pju-** [getkirby/panel#1120] opened 2017-11-15 08:38 UTC
It seems to me that you explicitly need to set **sortable: true** for files in the blueprints in 2.5.7.
For a while (not sure which version it started with) that was not necessary, as files were sortable by default.

I'd argue that it makes more sense to have it default to true.

/e: To elaborate: The changed behaviour might be important to mention somewhere because for a few of my clients' pages it "broke" the backend because they couldn't sort their files anymore.

**Comment by lukasbestle** [comment] 2017-11-28 21:20
It is actually intended that this feature isn't enabled by default, as sorting files generates file meta files. If you don't actually do anything with the order of the files in your templates, it just doesn't make sense to generate those files.

I just tracked down why file sorting was enabled by default in previous version. It was actually a bug that was caused by our new permissions feature in Kirby 2.4.0 and has been [fixed in Kirby 2.5.3](https://github.com/getkirby/panel/pull/1012).

**Closed by lukasbestle** 2017-11-28 21:20 UTC
